Fix missing main.handlebars file
This commit will fix :

Error: ENOENT: no such file or directory, open 'simple-express-handlebars-boilerplate\views\layouts\main.handlebars'